name: CI

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.22.x'

      - name: Install Dependencies
        run: make GOBIN=$HOME/gopath/bin deps

      - name: Run Tests
        run: make GOBIN=$HOME/gopath/bin test

      - name: Run Coverage Tests
        env:
          COVERALLS_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
        run: |
          $HOME/gopath/bin/goveralls -v -service=github

      - name: Build Project
        if: github.ref == 'refs/heads/master'
        run: make GOBIN=$HOME/gopath/bin build

      - name: Build Docker Image
        if: github.ref == 'refs/heads/master'
        run: docker build -t clintsharp/gogen .

      # Deployment: These steps run only on the master branch.
      - name: Configure AWS Credentials
        if: github.ref == 'refs/heads/master'
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1

      - name: Deploy Build Artifacts to S3
        if: github.ref == 'refs/heads/master'
        run: aws s3 sync build s3://gogen-artifacts --delete

      - name: Run Docker Push Script
        if: github.ref == 'refs/heads/master'
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: bash docker-push.sh

  deploy-lambdas:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.13'
          
      - name: Set up Python virtual environment
        run: |
          python -m pip install --upgrade pip
          python -m venv .pyvenv
          source .pyvenv/bin/activate
          pip install boto3 botocore awscli
          
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1
          
      - name: Deploy Lambda Functions
        env:
          LAMBDA_ROLE_ARN: ${{ secrets.LAMBDA_ROLE_ARN }}
        run: |
          source .pyvenv/bin/activate
          cd gogen-api
          # Run the deployment script
          ./deploy_lambdas.sh 